on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  Build-Project:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
      - name: Cache
        uses: actions/cache@v4.2.3
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: Library
          # An explicit key for restoring and saving the cache
          key: Library-Demo-WebGL
          # An ordered multiline string listing the prefix-matched keys, that are used for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.
          restore-keys: |
                    Library-Demo-
                    Library-

      - name: Build Unity Project
        # You may pin to the exact commit or the version.
        # uses: game-ci/unity-builder@3b26780ddfe24a0ee2aebb0a65297ab69fc5bb4c
        uses: game-ci/unity-builder@v4.5.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          # Platform that the build should target.
          targetPlatform: WebGL 
          # Name of the build. Should not include a file extension.
          buildName: Release
      - name: Store Build
        uses: actions/upload-artifact@v4.6.2
        with:
          # Artifact name
          name: Build
          # A file, directory or wildcard pattern that describes what to upload
          path: build

  Upload-To-Itch:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    needs: Build-Project
    steps:
      - name: Itch.io - Publish
        # You may pin to the exact commit or the version.
        # uses: KikimoraGames/itch-publish@ea06fdc7e36b34a6c4f88b379a73f3362537b998
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          # Butler API Key
          butlerApiKey: ${{ secrets.ITCH_API }}
          # Directory or .zip file of the game data. Zip files are slower to upload.
          gameData: Build.zip
          # Itch.io username of the game owner. e.g. in finji/overland this would be finji.
          itchUsername: spyderweb-studios
          # Itch.io id of the game. e.g. in finji/overland this would be overland.
          itchGameId: Demo
          # Channel name of the game: https://itch.io/docs/butler/pushing.html#channel-names
          buildChannel: WebGL
            
